name: Pages

on:
  workflow_dispatch: {}
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Build
        run: |
          docker build -t env .devcontainer
          docker run --rm -u $(id -u):$(id -g) -v $PWD:/workspace -w /workspace env bun ci
          docker run --rm -u $(id -u):$(id -g) -v $PWD:/workspace -w /workspace env bun run fetch
          docker run --rm -u $(id -u):$(id -g) -v $PWD:/workspace -w /workspace env bun x vite build --base ${{ steps.pages.outputs.base_path }}

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
